### ISSUE TITLE
Auth Server: Make Auth Server Generic to Support Any Identity Provider (IDP)

### ISSUE THREAD

**Issue by dheerajoruganty** [agentic-community/mcp-gateway-registry#65]
## Problem Statement

Currently, the auth server is tightly coupled to AWS Cognito with some OAuth2 support. This limits flexibility and requires code changes to support new identity providers like KeyCloak, Google, Auth0, etc. As development velocity increases, we need a more extensible architecture.

## Goals

- **Generic IDP Support**: Support any identity provider without code changes
- **High Development Velocity**: Easy to add new IDPs quickly
- **Standard Protocols**: Support OAuth2/OIDC, SAML, LDAP, and custom APIs
- **Backward Compatibility**: Maintain existing Cognito functionality
- **Configuration-Driven**: Add new IDPs through configuration, not code

### 1. Plugin Architecture
Create a standard interface for IDP plugins:

```python
class IDPPlugin(ABC):
    @abstractmethod
    async def validate_token(self, token: str, config: dict) -> ValidationResult
    
    @abstractmethod
    async def get_user_info(self, token: str, config: dict) -> UserInfo
    
    @abstractmethod
    def get_auth_url(self, config: dict, state: str, redirect_uri: str) -> str
    
    @abstractmethod
    def supports_protocol(self) -> List[str]  # ['oauth2', 'oidc', 'saml']
```

### 2. Configuration-Driven Protocol Handlers

Support IDP profiles through configuration:

```yaml
idp_profiles:
  keycloak:
    protocol: oidc
    endpoints:
      auth: "${KEYCLOAK_URL}/auth/realms/${REALM}/protocol/openid-connect/auth"
      token: "${KEYCLOAK_URL}/auth/realms/${REALM}/protocol/openid-connect/token"
      userinfo: "${KEYCLOAK_URL}/auth/realms/${REALM}/protocol/openid-connect/userinfo"
      jwks: "${KEYCLOAK_URL}/auth/realms/${REALM}/protocol/openid-connect/certs"
    field_mappings:
      username: preferred_username
      email: email
      groups: groups
    token_validation:
      method: jwt_jwks
      audience_required: true
```

### 3. Standardized Output Format

Ensure all IDPs return consistent user information:

```python
@dataclass
class AuthResult:
    valid: bool
    user_id: str
    username: str
    email: Optional[str]
    groups: List[str]
    scopes: List[str]
    metadata: Dict[str, Any]
    expires_at: Optional[datetime]
    method: str  # 'jwt', 'session', 'api_key'
```

## Suggested Directory Structure

```
auth-server/
├── core/
│   ├── interfaces.py      # Standard interfaces
│   ├── auth_result.py     # Standardized output
│   └── config_loader.py   # Configuration management
├── protocols/
│   ├── oauth2.py         # Generic OAuth2/OIDC handler
│   ├── saml.py           # SAML handler
│   └── ldap.py           # LDAP handler
├── plugins/
│   ├── cognito.py        # AWS Cognito plugin
│   ├── keycloak.py       # KeyCloak plugin
│   ├── google.py         # Google plugin
│   └── github.py         # GitHub plugin
├── config/
│   ├── templates/        # IDP templates
│   └── profiles/         # Environment-specific configs
└── main.py
```

### Phase 1: Foundation
- [ ] Extract current Cognito code into a plugin
- [ ] Create standard interfaces and base classes
- [ ] Implement configuration loader with template support
- [ ] Create standardized AuthResult format

### Phase 2: Generic OIDC Support
- [ ] Implement generic OAuth2/OIDC protocol handler
- [ ] Add OIDC discovery endpoint support (`.well-known/openid_configuration`)
- [ ] Create templates for common IDPs (Google, GitHub, Auth0)
- [ ] Add automatic JWKS endpoint detection

### Phase 3: Enterprise Support
- [ ] Add SAML protocol handler
- [ ] Add LDAP protocol handler
- [ ] Create templates for enterprise IDPs (Okta, ADFS)

### Phase 4: Advanced Features
- [ ] Hot-reload configuration without restart
- [ ] Multi-IDP support in single instance
- [ ] Advanced caching strategies
- [ ] Comprehensive testing framework

## Development Velocity Optimizations

- **Auto-Discovery**: Automatic endpoint detection for OIDC providers
- **Configuration Templates**: Pre-built configs for popular IDPs
- **Smart Defaults**: Sensible defaults to minimize configuration
- **Hot-Reload**: Change configurations without restarts
- **Validation**: Config validation with helpful error messages

## Target IDPs to Support

**Immediate Priority:**
- KeyCloak
- Google OAuth2
- GitHub OAuth2
- Auth0

**Future Support:**
- Okta
- Microsoft ADFS
- Azure AD
- Custom LDAP

## Benefits

1. **No Code Changes**: Add new IDPs through configuration only
2. **Faster Integration**: Templates and auto-discovery reduce setup time
3. **Better Testing**: Standardized interfaces enable better testing strategies
4. **Easier Maintenance**: Clear separation of concerns
5. **Future-Proof**: Easy to add new protocols and IDPs

## Breaking Changes

This should be implemented as a backward-compatible refactor. Existing Cognito configurations should continue to work without changes.

## Questions for Discussion:

1. Would we prefer this to be a single binary with all plugins or a microservices approach?
2. What would the configuration source preference be, would it be files, environment variables, or external config service?
3. Testing strategy for multiple IDPs without requiring actual IDP instances? (I think this is not possible, but might be wrong.)
